version: '2.2'
services:
  signal_database:
    image:          postgres:11
    container_name: postgres_database
    restart:        always
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES:       abusedb, accountdb, keysdb, messagedb
      PGDATA:            /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_database:/var/lib/postgresql/data
  redis_main:
    image: redis:5
    container_name: redis_main
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis_main:/data
  redis_replication:
    image: redis:5
    container_name: redis_replication
    restart: always
    command: redis-server --port 6380
    ports:
      - '6380:6380'
    volumes:
      - ./redis_replication:/data
  
  # Remove linse below if you don't want PostgresDB management GUI
  signal_adminer:
    container_name: signal_adminer
    image:          adminer:latest
    ports: 
      - 8000:8080
    links: 
      - signal_database
    environment: 
      ADMINER_DESIGN: nette
    networks:
      - default
      
  # Remove linse below if you don't want Redis management GUI
  redis_commander:
    container_name: redis_commander
    image:          rediscommander/redis-commander:latest
    hostname: redis-commander
    ports: 
      - 8001:8081
    links: 
      - redis_main
      - redis_replication
    environment: 
      - REDIS_HOSTS=main:redis_main:6379, replica:redis_replication:6380
